config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  root 'transactions#dashboard'

end

app/models/history.rb
class History < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

  def self.balance
    credits = 0
    debits = 0
    self.all.each do |transaction|
      credits += transaction.amount if transaction.debit_or_credit == "Credit"
      debits += transaction.amount if transaction.debit_or_credit == "Debit"
    end
    @balance = credits - debits
  end

  def self.total_current_month
    @total_current_month = 0
    current_time = Time.now
    current_month = current_time.mon
    self.all.each do |transaction|
      if ((transaction.debit_or_credit == "Debit") && (transaction.created_at.mon == current_month))
        @total_current_month += transaction.amount
      end
    end
    @total_current_month
  end

  def self.total_previous_month
    @total_previous_month = 0
    current_time = Time.now
    previous_month = current_time.mon - 1
    self.all.each do |transaction|
      if ((transaction.debit_or_credit == "Debit") && (transaction.created_at.mon == previous_month))
        @total_previous_month += transaction.amount
      end
    end
    @total_previous_month
  end

  def self.transactions_current_month
    @transactions_current_month = 0
    current_time = Time.now
    current_month = current_time.mon
    self.all.each do |transaction|
      if (transaction.created_at.mon == current_month)
        @transactions_current_month += 1
      end
    end
    @transactions_current_month
  end

  def self.transactions_previous_month
    @transactions_previous_month = 0
    current_time = Time.now
    previous_month = current_time.mon - 1
    self.all.each do |transaction|
      if transaction.created_at.mon == previous_month
        @transactions_previous_month += 1
      end
    end
    @transactions_previous_month
  end

  def self.biggest_expense_current_month
    @biggest_expense_current_month = 0
    current_time = Time.now
    current_month = current_time.mon
    self.all.each do |transaction|
      if (transaction.created_at.mon == current_month) && (transaction.amount > @biggest_expense_current_month) && (transaction.debit_or_credit == "Debit")
        @biggest_expense_current_month = transaction.amount
      end
    end
    @biggest_expense_current_month
  end

  def self.biggest_expense_ever
    @biggest_expense_ever = 0
    self.all.each do |transaction|
      if (transaction.amount > @biggest_expense_ever) && (transaction.debit_or_credit == "Debit")
        @biggest_expense_ever = transaction.amount
      end
    end
    @biggest_expense_ever
  end

  def self.place_spent_most_money
    @place_spent_most_money = ""
    @most_money = 0
    self.all.each do |transaction|
      name = transaction.description
      place_total = transaction.amount
        self.all.each do |t|
          if t.description == name
            place_total += t.amount
          end
        end
      if place_total > @most_money
        @place_spent_most_money = transaction.description
      end
    end
    @place_spent_most_money
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def dashboard
    @transactions = Transaction.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:description, :amount, :debit_or_credit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :debit_or_credit, 'Credit' %>
    <%= f.radio_button :debit_or_credit, 'Credit', :value => 'Credit'%>
    <%= f.label :debit_or_credit, 'Debit' %>
    <%= f.radio_button :debit_or_credit, 'Debit', :checked => true, :value => 'Debit' %>
  </div>
  <div class="actions">
    <button id="checkout">Submit</button>
  </div>
<% end %>

app/views/transactions/dashboard.html.erb
<% if @transactions.balance < 0 %>
  <p id="warning">What are you thinking?!?! You can't have a negative balance! Make a deposit!!! RIGHT NOW!</p>
<% end %>

<h1>Dashboard</h1>

<p>
  <strong>Total Amount Of Money In Your Account: </strong>
    <% if @transactions.balance < 0 %>
      <font color=red><%= number_to_currency(@transactions.balance) %></font>
    <% else %>
      <font color=green><%= number_to_currency(@transactions.balance) %></font>
    <% end %>
</p>

<p>
  <strong>Total Number Of Transactions: </strong>
  <%= @transactions.size %>
</p>

<p>
  <strong>Total Amount Spent Current Month: </strong>
  <%= number_to_currency(@transactions.total_current_month) %>
</p>

<p>
  <strong>Total Amount Spent Previous Month: </strong>
  <%= number_to_currency(@transactions.total_previous_month) %>
</p>

<p>
  <strong>Total Transactions Current Month: </strong>
  <%= @transactions.transactions_current_month %>
</p>

<p>
  <strong>Total Transactions Previous Month: </strong>
  <%= @transactions.transactions_previous_month %>
</p>

<p>
  <strong>Biggest Expense Current Month: </strong>
  <%= number_to_currency(@transactions.biggest_expense_current_month) %>
</p>

<p>
  <strong>Biggest Expense Ever: </strong>
  <%= number_to_currency(@transactions.biggest_expense_ever) %>
</p>

<p>
  <strong>Place Spent The Most Money: </strong>
  <%= @transactions.place_spent_most_money %>
</p>

<br>

<%= link_to 'List Of Transactions', transactions_path %><br>
<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Of Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Amount</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.description %></td>
        <td><%= number_to_currency(transaction.amount) %></td>
        <td><%= transaction.debit_or_credit %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dashboard', root_path %><br>
<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@transaction.amount) %>
</p>

<p>
  <strong>Debit or credit:</strong>
  <%= @transaction.debit_or_credit %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>